[package]
name = "clap_complete_all"
version = "0.1.0"
edition = "2024"
resolver = "2"

[dependencies]
clap = "4.5"
clap_complete = "4.5"
clap_complete_nushell = "4.5"

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
